version: '3.8'

services:

  react-app:
    build:
      context: ./client
    container_name: react-app
    volumes:
      - react_build:/app/build
    working_dir: /app
    command: sh -c "npm install && npm run build"


  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - react-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - react_build:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  react_build: