version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html
  
  react-app:
    build:
      context: ./client
    container_name: react-app
    command: sh -c "npm install && npm run build"
    volumes:
      - ./client:/app
    working_dir: /app
