version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./client/build:/usr/share/nginx/html
    command: >
      sh -c "
        certbot certonly --webroot --webroot-path=/usr/share/nginx/html \
        --email arbofficial02@email.com --agree-tos --no-eff-email \
        -d areebhanas.studio -d www.areebhanas.studio &&
        trap exit TERM; while :; do certbot renew --webroot -w /usr/share/nginx/html; sleep 12h & wait $${!}; done;
      "

  react-app:
    build:
      context: ./client
    container_name: react-app
    command: sh -c "npm install && npm run build"
    volumes:
      - ./client:/app
    working_dir: /app
