version: '3.8'

services:

  react-app:
    build:
      context: ./client
    container_name: react-app
    volumes:
      - react_build:/app/build
    working_dir: /app
    command: sh -c "npm install && npm run build"
    env:
      DOCKER_BUILDKIT: 1


  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - react-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - react_build:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/ssl
      - /etc/ssl/areebhanas:/etc/ssl/areebhanas:ro


volumes:
  react_build: