name: CI/CD Pipeline to Azure VM

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Build React App
        run: npm run build

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SCP Files to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "docker-compose.yml,client/build,client/nginx.conf,client/Dockerfile,certs,certs-data"
          target: "/home/${{ secrets.AZURE_USER }}/portfolio"

      - name: SSH and Deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e
            sudo systemctl enable docker
            sudo systemctl start docker
            cd /home/${{ secrets.AZURE_USER }}/portfolio
            docker-compose down || true
            docker-compose up -d --build

